[package]
name = "apt-downgrade"
version = "0.1.0"
authors = ["desbma <desbma@users.noreply.github.com>"]
edition = "2018"

[profile.release]
panic = "abort"

[dependencies]
clap = "2"
deb-version = "0.1"
glob = "0.3"
itertools = "0.8"
lazy_static = "1.4"
